baseURL = "https://www.basketgardolo.it/"
languageCode = "it"
title = "Basket Gardolo"
metaDataFormat = "yaml"
[taxonomies]
  categoria = "categorie"
  "partite/squadre" = "partite/squadra"
  stagione = "stagioni"
  giocatore = "giocatori"
  allenatore = "allenatori"

[[menu.main]]
  name = "Home" 
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "La Società"
  url = "/societa/"
  identifier = "fa fa-home"
  weight = 2

[[menu.main]]
  name = "Le Squadre"
  url = "/stagioni/2020-2021"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "News"
  url = "/news/"
  identifier = "fa fa-list"
  weight = 4

[[menu.main]]
  name = "Calendari"
  url = "/calendari"
  identifier = "fa fa-sitemap"
  weight = 5

[outputs]
  section = ["HTML", "JSON"]