baseURL = "http://example.org/"
languageCode = "it"
title = "Basket Gardolo"
theme = "hugo-future-imperfect"
[taxonomies]
  "categorie" = "categoria"
  "partite/squadre" = "partite/squadra"
[[menu.main]]
  name = "Home" 
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "Partite"
  url = "/partite/"
  identifier = "fa fa-home"
  weight = 2

[[menu.main]]
  name = "Squadre"
  url = "/squadre/"
  identifier = "fa fa-newspaper-o"
  weight = 3

[[menu.main]]
  name = "Giocatori"
  url = "/giocatori/"
  identifier = "fa fa-list"
  weight = 4

[[menu.main]]
  name = "Stagioni"
  url = "/stagioni/"
  identifier = "fa fa-sitemap"
  weight = 5

[[menu.main]]
  name = "Iscrizione"
  url = "/iscrizione/"
  identifier = "fa fa-envelope-o"
  weight = 6