backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Immagine", name: "image", widget: "image"}
      - {label: "Testo", name: "body", widget: "markdown"}
  - name: "giocatori" # Used in routes, e.g., /admin/collections/blog
    label: "Giocatori" # Used in the UI
    folder: "content/giocatori" # The path to the folder where the documents are stored
    format: "yaml-frontmatter"
    nested: {depth: 1000}
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Nome", name: "title", widget: "string"}
      - {label: "Ruolo", name: "ruolo", widget: "string"}
      - {label: "Numero", name: "numero", widget: "number"}
    meta: { path: { widget: string, label: 'Path', index_file: '_index', pattern: ['.*', "Error"] } }