---
new_page_extension: md
auto_deploy: false
admin_path: ""
webhook_url:
sections:
  - type: directory
    path: content/pagine/**/*
    label: Pagine
    create: all
    match: "**/*"
  - type: directory
    path: content/news/**/*
    label: News
    create: all
    match: "**/*"
  - type: directory
    path: content/giocatori
    label: Giocatori
    create: all
    match: "**/_index.md"
    templates:
      - giocatore
  - type: directory
    path: content/stagioni
    label: Stagioni
    create: all
    match: "**/*.md"
  - type: directory
    path: content/partite
    label: Partite
    create: all
    match: "**/*"
    templates:
      - partite
  - type: directory
    path: content/squadre
    label: Squadre
    create: all
    match: "**/*"
    templates:
      - squadreb
  - type: directory
    path: content/sponsors
    label: Sponsor
    create: all
    match: "**/*.md"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
    - HUGO_ENV=staging
    - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
